### ISSUE TITLE
Any harm in enabling both HTTP/2 and Service Worker push?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [o10n-x/wordpress-http2-optimization#5]
Is this safe to do or will it result in duplicate asset downloads?

**Comment by optimalisatie** [comment]
Hi Ahmed,

Thank you for your question!

In regards to HTTP/2 Server Push vs Service Worker Push. 

Service Worker Push is a unique innovation provided by the [PWA / Service Worker optimization plugin](https://github.com/o10n-x/wordpress-pwa-optimization). It is a unique solution (doesn't exist in any other project). It can provide a much better result than HTTP/2 Push and it opens the door to more advanced solutions for preloading assets.

HTTP/2 Server Push does not seem to offer an advantage without the complex Cache Digest solution. It may be better to abandon it in favor for the Service Worker.

Performance study: https://calendar.perfplanet.com/2016/cache-digests-http2-server-push/
Google engineer: https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

Service Worker Push has access to the browser cache and knows what resources are already downloaded. This makes it much more efficient than HTTP/2 which by default keeps pushing (downloading) asset data on each request. While there is a proposal for a "Cache-Digest" solution that uses a complex "cache hash" calculation to inform the server what files are already cached in the browser, that isn't a official solution yet (not yet supported by most servers, not even CloudFlare) and it isn't as reliable (calculating a small cache hash from hundreds of thousands of cache objects can't be accurate) while the Service Worker Push solution has direct efficient access to the Cache storage so that it can support millions of cached files with maximum efficiency and speed.

Service Worker push provides many other advantages. For example, Service Worker Push enables to preload a complete page + all essential assets for offline usage on the basis of a single page URL. This is a unique capability that supports millions of pages that each contain unique images and assets. It is easy and reliable. As a web developer you simply need to attach assets to a page using a PHP method (`\O10n\attach_asset`)

An other advantage: when a visitor views a website, there is a lot of idle time. This time can be used for smart preloading so that assets are available with zero wait when the user need them. Because of this (when used correctly) Service Worker Push can be much faster than HTTP/2 Server Push as it doesn't need to be bound to "user action".

Service Worker Push enables advanced optimization. It would be possible for example to preload just the above the fold images based on the view port and to adapt a tailored lazy loading system so that there is no flicker effect during a page load, while you can achieve a perfect mobile Google Lighthouse score for pages with hundreds of images. As a technology, it provides many other unique optimization abilities / solutions.

From a optimization perspective, we would advise to just use Service Worker Push (no HTTP/2 Push).

An example is www.verkoop.com. You can notice that it has a smart preload system that uses the distance to the mouse and mouse events (to start pushing images in the background, like HTTP/2 Server Push, but then using Service Worker Push with a smart logic for Service Worker based above the fold optimization). It uses a regular Web Worker for preloading that is terminated as soon as a user starts to navigate so that it's efficient and always fast. The Web Worker communicates with the Service Worker. This solution has recently been added to the PWA optimization plugin as well.

![image](https://user-images.githubusercontent.com/8843669/41453971-00d1a1dc-7078-11e8-8d5e-b122bc892143.png)

I hope that this information is helpful!
